# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterchess', '0004_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='game',
            field=models.IntegerField(null=True),
        ),
    ]
