# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterchess', '0006_game_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_collation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
